# Generated by Django 2.0.4 on 2018-05-02 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 19, 47, 15, 923126), verbose_name='发送事件'),
        ),
    ]
